# Generated by Django 3.1.2 on 2020-10-09 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DonManuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdSlider', models.CharField(max_length=120)),
                ('Slider', models.ImageField(null=True, upload_to='slider')),
            ],
        ),
        migrations.AddField(
            model_name='misvis',
            name='tit1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='misvis',
            name='tit2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
