# Generated by Django 3.1.2 on 2020-11-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonManuel', '0002_auto_20201009_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('num_con', models.AutoField(primary_key=True, serialize=False)),
                ('nom_con', models.CharField(max_length=50)),
                ('ape_con', models.CharField(max_length=50)),
                ('asu_con', models.CharField(max_length=50)),
                ('tco_con', models.CharField(max_length=10)),
                ('msg_con', models.TextField(max_length=200)),
            ],
        ),
    ]
