# Generated by Django 3.1.2 on 2020-10-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('num_fot', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fot', models.CharField(max_length=40)),
                ('des_fot', models.TextField()),
                ('foto', models.ImageField(null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='MisVis',
            fields=[
                ('num_misvis', models.AutoField(primary_key=True, serialize=False)),
                ('txt1', models.TextField()),
                ('txt2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('num_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=120)),
                ('pre_pro', models.IntegerField()),
                ('sto_pro', models.IntegerField()),
                ('des_pro', models.TextField()),
            ],
        ),
    ]
